### ISSUE TITLE
[BUG] Image docs/formal_verification/proof not found

### ISSUE THREAD

**Issue by chrc** [octo-technology/OpenTezos#17]
En phase wip, le fichier `docs/formal_verification/introduction.md` lève une erreur à la compilation.
![Capture d’écran 2021-03-12 à 13 53 21](https://user-images.githubusercontent.com/88607/110942805-9cfb7880-833a-11eb-86a2-87c500a14ab0.png)

**Comment by AymericBethencourt** [comment]
Thanks, it's been fixed
