### ISSUE TITLE
Bad links to Position Paper and White Paper

### ISSUE THREAD

**Issue by kevinelliott** [octo-technology/OpenTezos#69]
On the Tezos Basics page (https://opentezos.com/tezos-basics) there are Page Not Found when clicking Position Paper and White Paper links.

**Comment by ThomasZoughebi** [comment]
Thank you @kevinelliott !
Every broken link (including references) in both "_Blockchain Basics_" and "_Tezos Basics_" modules will work correctly after merging :)
